{% set name = "aggdraw" %}
{% set version = "1.3.11" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9803aea0c06dc74ffb3b3eb19d613efe719e7c89940bcdb617ede202b390e8e

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - freetype
  run:
    - python
    - pillow

test:
  imports:
    - aggdraw
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://github.com/pytroll/aggdraw
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: High quality drawing interface for PIL.
  description: 'The aggdraw module implements the basic WCK 2D Drawing Interface on
    top of the AGG library. This library provides high-quality drawing,
    with anti-aliasing and alpha compositing, while being fully compatible
    with the WCK renderer.'
  doc_url: ''
  dev_url: https://github.com/pytroll/aggdraw

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
