{% set name = "aggdraw" %}
{% set version = "1.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8536d8a88d361dcb0297a1c059f263e650c6ede73164943ad3a1eb0c49a1573e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - freetype
  run:
    - python
    - pillow

test:
  imports:
    - aggdraw
  commands:

about:
  home: https://github.com/pytroll/aggdraw
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: High quality drawing interface for PIL.
  description: The aggdraw module implements the basic WCK 2D Drawing Interface on top of the AGG library. This library provides high-quality drawing, with anti-aliasing and alpha compositing, while being fully compatible with the WCK renderer.
  doc_url: ''
  dev_url: https://github.com/pytroll/aggdraw

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
