appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LxPJYD/Ioo52D/BE53hymWUiQHN1m19aZYWXr3qIkAQIWukLbjsz4IDeQfbAUf6d+4CHbk3GgB8V2F98ANW4E/meShGXQQcPMpy0esCcEoK+WbPBG0C14ovrFm0nbHSiPqQG5sklI0hntKhbDhCLKg2lTZ7GXGmy0xBXbmiKN1sh/KE4jeACoRCYlRSJxNmfepTfhzUetm9Z9r188x6fe+p17U/HGMRaWhgyL49zDapwqKGF8zpTwO85AEIRR6he+z+fEPTOarFSjZI3PAaniPEKSJqgNtIjdpwHUIygMmZbL55csxnF/zBqPx9wZk0uyYshNkG+5w7vN18+7w62nNOPLZcs8H5E9qCL2z7wHug3N5AMcWt8P8ZcTVqC670BezwHA8lVnGmlpi56xuxb4Y+vUBH1j6pWLbl3siOP06epHzBYCayTIhCWwJLfMEjd5ymaVtuWbiTF8LcHSGl9sSvxtREf8O4ZfAzjOPpMgJsjsdkbrDYXvwqHkO7u31GB6kvArXbO/ZtOtGDMDeK5tOmKX+geNjpZNNgfLgoeQhKfH2uJf7vzhmL4x3kNRGPviY8TGq7rw6P2imP69uyz6KT+q28hWu/5baj0h9tjNxtM5eDic5beq4BWYWlBu8IqZrhDEcXu5uVmz33bkJUOI568/wCwwlctj5QwPef6Nrs=}
provider:
  win: azure
