travis:
  secure:
    BINSTAR_TOKEN: I0n8K8LTjZjVU0TBvQc1Jno2BYcENJ1HOz/g2mZunjxbVek2IgSwc8p1jd/cd8T8hDhwWPIybmvYnuVam/vaNnf2B/3cW+I4kQD7Ae5Ar0cDjJca97lhcy5zAH00jccI7ALv6/FFLvEwWMVg458RfsrWtW8DEra6IGTm3UAEetnOSeXqwz2ze9RZRMzGxzYqi3u7HuxmMuc46XcERx9FUFJq2kAWVzYQll0Pm9/3eL4FPl+tuKZBENpkhIrE/1aMOco0Hmypz05iw0evwPyec8ADRncCTnFc5aAjAYAPN+nj62QJ87EuWij9JVMUAux77rtwub7Z7owBzemfiHp4X6S7FN4uN3MAppG9yMPmtsaRu9T/5nxD2wTcQefX2xqRURWx2mG1kd23P/p4/PeaLfaqsvEsq4GIN5YvE+OXbywmTfa7RJumroo3KDmUgswcLI46WmWQBzNciPRP8RrRrWBTUea/MoWazxjJr2ld8CbHxw20A3NWRpcYd2Dav2dFfmNbUojQ/770HptsR76eZpOp2JFWH+euK0J34hAmTF/vry0XSa7I0sT5CDZp/k1Dnv/jSivwN32lyShWWkazXiJhGJbfQ0NF3AT5Lrcrz1BBPmr1EDPDSnez5UqiSoE7b+k1shgxROjtxuj4MEeywma6m2tId99xXmvGn4yEl5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
