travis:
  secure:
    BINSTAR_TOKEN: Uy82gNYBrNabia/wcAK7OUtkMz8ZuzjD46pTbs2H5bIr0+Rved/LqBZC+zG/m6iBF4Ja1koP5hP3nouM0KYCUmFzNGRTH/a3cysnzAMUmI9eSBYoU0cR/U8WqPdRQkOWD6VzmycHmRTQgG1fNx8Q/tOXdpgS9HOFxR5y7nrpUjGqAnOrnwS7GZXYT0pi1CKY+hk1fTVAotWYDhy/pYuWxSuALltu39WuVyrZsfWXImC8dUvaor3gEGqQjdywJvQhtitYMG7ewfDuAmGWGjYIR7Qd7+cXi0tt0WVxTlRiqCCj5US15WSCYV9JYjyjJQ5YLCAoGjEUNiL4CHIW8yBx1SJm7Zj9fF5STDlZBkxYhrVDetFIbnBHMtNxrTMVJDheTjH4bVuxj168eFjfJ++f95DhgX9MqNSG6m6R6QWKUdNO/iV7t0f2SG18RaBn5teTi5KrvyBAg/99j2Cs+0RixnpBB7gvJ3ixIqIzaHG4V+Eu53UTXK/BrhVFckBqpbb05hlHNLCeDzkU6JNrcaLnPJDOiHCLEyS9l3Edv9lfTf+6uNwbGMdqqhwOKRVFepIXXSZD9CjBWgm819tzRHvr82sfWF01Zr4X3KKTqQ45nE7WE92WqTFzlCTGUB1jPdHosJPlJc+GtKz00rnMyTcTJIXF4O/quciSIxOlOY2vzpc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
